'use client';

import { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useJourneyStore } from '@/lib/store/journeyStore';
import { useUIStore } from '@/lib/store/uiStore';
import { lines } from '@/content/lines';
import housesRaw from '@/content/houses.json';
import type { ScoredIdea } from '@/lib/scoring/types';

interface LineageFigure { name: string; sharedTraitLine: string }
interface House {
  id: string; name: string; hex: string; tagline: string;
  description: string; strengths: string[]; lineage: LineageFigure[];
}
const HOUSES = housesRaw as unknown as House[];
const WHATSAPP_NUMBER = '919686917041';

/**
 * S11 — Founder Profile
 *
 * 6 sections: Card, House identity, Top 3 ideas, BUILD IT CTA (hidden),
 * Download .md, consultation reveal.
 */
export function S11Profile() {
  const state = useJourneyStore();
  const enqueueMessage = useUIStore((s) => s.enqueueMessage);

  const [showConsultation, setShowConsultation] = useState(false);
  const [aboutExpanded, setAboutExpanded] = useState(false);
  const [downloadError, setDownloadError] = useState('');
  const dialogueSent = useRef(false);
  const cardRef = useRef<HTMLDivElement>(null);

  const house = HOUSES.find((h) => h.id === state.houseId) || HOUSES[0];
  const crowned = state.matchedIdeas
    ? [state.matchedIdeas.nest, state.matchedIdeas.spark, state.matchedIdeas.wildvine]
        .find((s) => s.idea.idea_id === state.crownedIdeaId) || state.matchedIdeas.nest
    : null;
  const allIdeas = state.matchedIdeas
    ? [state.matchedIdeas.nest, state.matchedIdeas.spark, state.matchedIdeas.wildvine]
    : [];
  const displayName = state.displayName || 'Founder';

  useEffect(() => {
    if (dialogueSent.current) return;
    dialogueSent.current = true;
    enqueueMessage({ speaker: 'cedric', text: lines.s11.cedric.intro, type: 'dialogue' });
    setTimeout(() => {
      enqueueMessage({ speaker: 'cedric', text: lines.s11.cedric.final(displayName), type: 'dialogue' });
    }, 3000);
    setTimeout(() => {
      enqueueMessage({ speaker: 'pip', text: lines.s11.pip.final, type: 'dialogue' });
    }, 5000);
  }, [enqueueMessage, displayName]);

  function generateMarkdown(): string {
    const whyYou = crowned ? (state.whyYouTexts[crowned.idea.idea_id] || 'Trust the match.') : '';
    const qs = crowned?.idea.quickStart;
    return `# ${crowned?.idea.idea_name || 'Your Idea'} — Your Catalst Founder Profile

**House:** ${house.name}
**Match:** ${crowned?.displayScore || 0}% in ${crowned?.idea.domain_primary.replace(/_/g, ' ') || 'unknown'}

## Your Top Idea
${crowned?.idea.idea_name || ''} — ${crowned?.idea.one_liner || ''}

${crowned?.idea.pain_to_promise || ''}

## Why This Fits You
${whyYou.replace('__loading__', 'Trust the match.')}

## First Steps
- Week 1: ${qs?.week1 || 'Validate the core assumption'}
- MVP: ${qs?.mvp || 'Build the simplest version'}
- First customers: ${qs?.firstCustomers || 'Talk to 10 people in the space'}

## Your Personality Profile
House: ${house.name} | Traits: ${state.crystalOrbs.join(', ')} | Strengths: ${house.strengths.join(', ')}

---
Generated by Catalst · catalst.app
`;
  }

  function handleDownload() {
    try {
      const md = generateMarkdown();
      const blob = new Blob([md], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `catalst-${house.id}-${displayName.toLowerCase().replace(/\s+/g, '-')}.md`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      setDownloadError('');
    } catch {
      setDownloadError('Download failed, try again');
    }
  }

  function getWhatsAppUrl() {
    const msg = encodeURIComponent(
      `Hi Anish! I just completed my Catalst journey.\nI'm a ${house.name} founder. My top idea is ${crowned?.idea.idea_name || 'my matched idea'} in ${crowned?.idea.domain_primary.replace(/_/g, ' ') || 'startups'}.\nI want to book a 30-min strategy call (₹500) to explore building it.`
    );
    return `https://wa.me/${WHATSAPP_NUMBER}?text=${msg}`;
  }

  return (
    <div className="flex flex-col gap-8 pb-8 overflow-y-auto">
      {/* ── Section 1: Founder Card ── */}
      <div ref={cardRef} className="mx-auto w-[300px] sm:w-[400px]">
        <div
          className="rounded-2xl p-6 flex flex-col items-center gap-4 text-center"
          style={{
            border: `2px solid ${house.hex}`,
            background: '#14171E',
            aspectRatio: '9 / 16',
          }}
        >
          {/* House name */}
          <p className="text-sm font-serif italic" style={{ color: house.hex }}>
            {house.name}
          </p>

          {/* User name */}
          <h2 className="text-xl font-bold tracking-wider uppercase text-ivory">
            {displayName}
          </h2>

          {/* Trait badges */}
          <div className="flex gap-2 flex-wrap justify-center">
            {state.crystalOrbs.slice(0, 3).map((orb) => (
              <span
                key={orb}
                className="text-[10px] px-2 py-0.5 rounded-full font-medium"
                style={{ backgroundColor: `${house.hex}20`, color: house.hex, border: `1px solid ${house.hex}30` }}
              >
                {orb}
              </span>
            ))}
          </div>

          {/* Radar silhouette (pure SVG shape, no labels/numbers/axes) */}
          <svg viewBox="0 0 100 100" className="w-24 h-24 opacity-40">
            <polygon
              points="50,15 85,40 75,80 25,80 15,40"
              fill={`${house.hex}15`}
              stroke={house.hex}
              strokeWidth="1"
            />
          </svg>

          {/* Match info */}
          {crowned && (
            <div>
              <p className="text-xs font-mono text-ivory-muted uppercase tracking-wider">
                {crowned.displayScore}% match · {crowned.idea.domain_primary.replace(/_/g, ' ')}
              </p>
            </div>
          )}

          {/* House tagline */}
          <p className="text-xs text-ivory/40 italic">{house.tagline}</p>

          {/* Lineage line */}
          <p className="text-[10px] text-ivory/30">
            {house.lineage.map((f) => f.name).join(' · ')}
          </p>

          {/* Footer */}
          <p className="text-[9px] text-ivory/20 mt-auto">catalst.app</p>
        </div>
      </div>

      {/* ── Section 2: House Identity ── */}
      <div className="space-y-3">
        <h3 className="text-2xl font-serif font-bold" style={{ color: house.hex }}>
          {house.name}
        </h3>
        <p className="text-sm text-ivory-muted leading-relaxed">{house.description}</p>
        <div className="space-y-2">
          {house.lineage.map((fig) => (
            <div key={fig.name} className="bg-dark-surface border border-white/10 rounded-lg p-3">
              <p className="text-sm font-semibold text-ivory">{fig.name}</p>
              <p className="text-[10px] text-ivory/40 mt-0.5">{fig.sharedTraitLine}</p>
            </div>
          ))}
        </div>
      </div>

      {/* ── Section 3: Top 3 Ideas ── */}
      <div className="space-y-2">
        <p className="text-xs font-mono text-ivory/30 uppercase tracking-widest">Your matched ideas</p>
        {allIdeas.map((si: ScoredIdea) => {
          const isCrowned = si.idea.idea_id === state.crownedIdeaId;
          return (
            <div
              key={si.idea.idea_id}
              className={`bg-dark-surface rounded-lg p-3 ${
                isCrowned ? 'border-2 border-gold/50' : 'border border-white/10'
              }`}
            >
              <div className="flex items-center justify-between">
                <p className={`text-sm font-semibold ${isCrowned ? 'text-gold' : 'text-ivory'}`}>
                  {si.idea.idea_name}
                </p>
                <span className="text-[10px] font-mono text-ivory/30">{si.displayScore}%</span>
              </div>
              <p className="text-xs text-ivory/40 mt-1 line-clamp-1">{si.idea.one_liner}</p>
            </div>
          );
        })}
      </div>

      {/* ── Section 4: BUILD IT CTA (hidden by default) ── */}
      {/* Revealed by Section 6's consultation trigger */}
      <AnimatePresence>
        {showConsultation && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: 'auto' }}
            exit={{ opacity: 0, height: 0 }}
            className="overflow-hidden"
          >
            <div className="bg-dark-surface border border-gold/20 rounded-2xl p-6 space-y-4">
              <p className="text-xs text-ivory/40 italic">
                The seed is ready. Now someone has to plant it.
              </p>
              <p className="text-[11px] font-mono text-ivory-muted uppercase tracking-widest">
                YOUR IDEA. 1 WEEK. CLAUDE CODE.
              </p>
              <h4 className="text-[22px] font-serif text-ivory leading-snug">
                Stop planning. Start shipping.
              </h4>
              <p className="text-sm text-ivory-muted leading-relaxed">
                I build founder MVPs with Claude Code and a team of AI specialists.
                One call to see if we're the right fit.
              </p>
              <span className="inline-block text-xs px-3 py-1 rounded-full border border-gold/40 text-ivory">
                ₹500 · 30 min · No fluff
              </span>
              <a
                href={getWhatsAppUrl()}
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center justify-center gap-2 w-full py-3.5 rounded-full bg-gold text-dark font-semibold text-sm hover:bg-gold/90 transition-all"
                style={{ height: 56 }}
              >
                <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347z"/><path d="M12 0C5.373 0 0 5.373 0 12c0 2.625.846 5.059 2.284 7.034L.789 23.492a.5.5 0 00.61.61l4.458-1.495A11.952 11.952 0 0012 24c6.627 0 12-5.373 12-12S18.627 0 12 0zm0 22c-2.347 0-4.518-.804-6.237-2.152l-.436-.355-3.276 1.098 1.098-3.276-.355-.436A9.956 9.956 0 012 12C2 6.486 6.486 2 12 2s10 4.486 10 10-4.486 10-10 10z"/></svg>
                Book Your Strategy Call →
              </a>

              {/* About the builder (collapsible) */}
              <div className="border-t border-white/10 pt-3 mt-2">
                <button
                  onClick={() => setAboutExpanded(!aboutExpanded)}
                  className="flex items-center gap-2 text-xs text-ivory/40 hover:text-ivory/60 transition-colors cursor-pointer w-full"
                >
                  <span className="transition-transform" style={{ transform: aboutExpanded ? 'rotate(90deg)' : 'rotate(0)' }}>›</span>
                  About the builder
                </button>
                <AnimatePresence>
                  {aboutExpanded && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: 'auto', opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.3 }}
                      className="overflow-hidden"
                    >
                      <div className="pt-3 space-y-2">
                        <p className="text-base font-semibold text-ivory">Anish Dutta</p>
                        <p className="text-[13px] text-ivory-muted">Product Manager · AI Builder · Mumbai</p>
                        <div className="flex flex-wrap gap-1.5">
                          {['Get Set Learn · EdTech PM', "Masters' Union · Merit Scholar", 'IIT Bombay · Agentic AI', 'Catalst · 7 iterations · 2 years'].map((c) => (
                            <span key={c} className="text-[10px] px-2 py-0.5 rounded-full bg-white/5 text-ivory/50 border border-white/10">
                              {c}
                            </span>
                          ))}
                        </div>
                        <a
                          href="https://in.linkedin.com/in/anish-dutta-4ba701282"
                          target="_blank"
                          rel="noopener noreferrer"
                          className="inline-block text-[11px] text-gold/60 hover:text-gold transition-colors underline underline-offset-2"
                        >
                          linkedin.com/in/anish-dutta-4ba701282
                        </a>
                        <p className="text-[13px] text-ivory-muted italic">
                          I've built this thing 7 times. I know what it takes to ship.
                        </p>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* ── Section 5 & 6: Download + Consultation trigger ── */}
      <div className="space-y-4">
        {/* Download .md */}
        <button
          onClick={handleDownload}
          className="w-full py-3.5 rounded-full border border-ivory/20 text-ivory font-semibold text-sm hover:border-ivory/40 hover:bg-white/5 transition-all"
          style={{ height: 56 }}
        >
          Download Your Idea Pack
        </button>
        {downloadError && (
          <p className="text-xs text-error text-center">{downloadError}</p>
        )}

        {/* Consultation reveal trigger */}
        {!showConsultation && (
          <button
            onClick={() => setShowConsultation(true)}
            className="w-full text-center text-xs text-ivory/30 hover:text-gold/60 transition-colors underline underline-offset-2 cursor-pointer"
          >
            Want expert help building this?
          </button>
        )}
      </div>

      {/* Journey complete footer */}
      <p className="text-[10px] text-ivory/20 text-center font-mono">
        {lines.s11.journeyComplete(house.name)}
      </p>
    </div>
  );
}
