'use client';

import { useState, useEffect, useRef, useCallback, useMemo } from 'react';
import { motion } from 'framer-motion';
import { useJourneyStore } from '@/lib/store/journeyStore';
import { useUIStore } from '@/lib/store/uiStore';
import { lines } from '@/content/lines';
import { analytics } from '@/lib/analytics';
import housesRaw from '@/content/houses.json';
import { ScreenQuote } from '@/components/ui/ScreenQuote';
import { MysticVaultCard } from '@/components/ui/MysticVaultCard';
import { FounderTradingCard } from '@/components/ui/FounderTradingCard';
import { computeFounderStats } from '@/lib/founder-stats';

interface LineageFigure { name: string; sharedTraitLine: string; quantified_impact?: string }
interface House {
  id: string; name: string; hex: string; tagline: string;
  description: string; strengths: string[]; lineage: LineageFigure[];
  collective_impact?: string;
}
const HOUSES = housesRaw as unknown as House[];

const ORB_COLORS: Record<string, string> = {
  Grit: '#F59E0B', Vision: '#F0D060', Craft: '#CD7F32', Influence: '#9B59B6',
  Empathy: '#00D8B9', Analysis: '#5DADE2', Freedom: '#BDC3C7', Stability: '#27AE60',
};

/**
 * S11 — Founder Profile (Batch 4 final).
 *
 * Layout:
 *   1. FounderTradingCard (9:16 holographic hero)
 *   2. Share row DIRECTLY below card (Instagram · WhatsApp · X · Download)
 *   3. House identity + description + lineage cards (unchanged from Batch 3)
 *   4. Top 3 ideas (unchanged)
 *   5. MysticVaultCard variant="full" at the bottom
 *
 * Uses `computeFounderStats` to derive rarity / speed / novelty / fit from
 * journey data deterministically per user.
 */
export function S11Profile() {
  const state = useJourneyStore();
  const enqueueMessage = useUIStore((s) => s.enqueueMessage);

  const [downloadError, setDownloadError] = useState('');
  const [cardSaving, setCardSaving] = useState(false);
  const dialogueSent = useRef(false);
  const cardRef = useRef<HTMLDivElement>(null);

  const house = HOUSES.find((h) => h.id === state.houseId) || HOUSES[0];
  const crowned = state.matchedIdeas
    ? [state.matchedIdeas.nest, state.matchedIdeas.spark, state.matchedIdeas.wildvine]
        .find((s) => s.idea.idea_id === state.crownedIdeaId) || state.matchedIdeas.nest
    : null;
  const allIdeas = state.matchedIdeas
    ? [state.matchedIdeas.nest, state.matchedIdeas.spark, state.matchedIdeas.wildvine]
    : [];
  const displayName = state.displayName || 'Founder';

  const orbData = useMemo(() => (
    state.crystalOrbs.slice(0, 3).map((name) => ({
      name,
      color: ORB_COLORS[name] || '#D4A843',
    }))
  ), [state.crystalOrbs]);

  const stats = useMemo(() => computeFounderStats({
    houseId: state.houseId,
    displayName,
    matchPercent: crowned?.displayScore || 0,
    noveltyScore: crowned?.idea.novelty_score,
    crystalOrbs: state.crystalOrbs,
    blotResponseTimes: state.blotResponseTimes,
    wordResponseTimes: state.wordResponseTimes,
    crystalSelectionTimes: state.crystalSelectionTimes,
    industryName: crowned?.idea.domain_primary?.replace(/_/g, ' ') || 'your industry',
  }), [state.houseId, displayName, crowned, state.crystalOrbs, state.blotResponseTimes, state.wordResponseTimes, state.crystalSelectionTimes]);

  useEffect(() => {
    if (dialogueSent.current) return;
    dialogueSent.current = true;
    analytics.complete(state.houseId || 'unknown', crowned?.idea.idea_name || 'unknown');
    enqueueMessage({ speaker: 'cedric', text: lines.s11.cedric.intro, type: 'dialogue' });
    setTimeout(() => enqueueMessage({ speaker: 'cedric', text: lines.s11.cedric.final(displayName), type: 'dialogue' }), 3000);
    setTimeout(() => enqueueMessage({ speaker: 'pip', text: lines.s11.pip.final, type: 'dialogue' }), 5000);
  }, [enqueueMessage, displayName, state.houseId, crowned]);

  const generateMarkdown = useCallback(() => {
    const whyYou = crowned ? (state.whyYouTexts[crowned.idea.idea_id] || 'Trust the match.') : '';
    const qs = crowned?.idea.quickStart;
    return `# ${crowned?.idea.idea_name || 'Your Idea'} — Your Catalst Founder Profile

**House:** ${house.name}
**Match:** ${crowned?.displayScore || 0}% in ${crowned?.idea.domain_primary?.replace(/_/g, ' ') || 'unknown'}
**Rarity:** ${stats.rarity.tier} — ${stats.rarity.label}
**Speed:** ${stats.responseSpeedRank.label}
**Novelty:** ${stats.noveltyDecile.label}
**Trait signature:** ${stats.traitSignature}

## Your Top Idea
${crowned?.idea.idea_name || ''} — ${crowned?.idea.one_liner || ''}

${crowned?.idea.pain_to_promise || ''}

## Why This Fits You
${whyYou.replace('__loading__', 'Trust the match.')}

## First Steps
- Week 1: ${qs?.week1 || 'Validate the core assumption'}
- MVP: ${qs?.mvp || 'Build the simplest version'}
- First customers: ${qs?.firstCustomers || 'Talk to 10 people in the space'}

## Your Personality Profile
House: ${house.name} | Traits: ${state.crystalOrbs.join(', ')} | Strengths: ${house.strengths.join(', ')}

---
Generated by Catalst · catalst.app
`;
  }, [crowned, house, state.crystalOrbs, state.whyYouTexts, stats]);

  function handleDownloadMd() {
    try {
      const md = generateMarkdown();
      const blob = new Blob([md], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `catalst-${house.id}-${displayName.toLowerCase().replace(/\s+/g, '-')}.md`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      analytics.cta('download');
    } catch { setDownloadError('Download failed, try again'); }
  }

  async function handleSaveCard() {
    if (!cardRef.current) return;
    setCardSaving(true);
    try {
      const { toPng } = await import('html-to-image');
      const dataUrl = await toPng(cardRef.current, { pixelRatio: 3, cacheBust: true });
      const a = document.createElement('a');
      a.href = dataUrl;
      a.download = `catalst-${house.id}-${displayName.toLowerCase().replace(/\s+/g, '-')}.png`;
      a.click();
      analytics.cta('download');
    } catch { setDownloadError('Card save failed, try again'); }
    setCardSaving(false);
  }

  const shareText = `I just found my startup idea on Catalst 🌱\n\nI'm a ${house.name} founder — ${stats.rarity.tier.toLowerCase()}, ${stats.rarity.label}.\nMy match: ${crowned?.idea.idea_name || 'my idea'} at ${crowned?.displayScore || 0}% fit.\n\nWhat founder are you? → catalst.app`;

  return (
    <div className="flex flex-col gap-6 pb-8 overflow-y-auto">
      {/* ── 1. Founder Trading Card (9:16 holographic hero) ── */}
      <div className="flex justify-center pt-2">
        <FounderTradingCard
          ref={cardRef}
          displayName={displayName}
          house={house}
          orbs={orbData}
          crownedIdeaName={crowned?.idea.idea_name}
          crownedIdeaDomain={crowned?.idea.domain_primary}
          matchPercent={crowned?.displayScore || 0}
          stats={stats}
        />
      </div>

      {/* ── 2. Share row directly below card ── */}
      <div className="max-w-sm mx-auto w-full px-4">
        <p className="text-[10px] text-ivory/35 uppercase tracking-widest text-center mb-2">
          Share your card
        </p>
        <div className="grid grid-cols-4 gap-2">
          <motion.button
            whileTap={{ scale: 0.94 }}
            onClick={() => {
              handleSaveCard();
              const t = encodeURIComponent('Card saved! Now open Instagram → Your Story → upload from gallery 📸');
              setTimeout(() => window.open(`https://wa.me/?text=${t}`, '_blank'), 300);
            }}
            data-testid="share-instagram"
            className="h-12 rounded-xl text-white text-[11px] font-medium bg-gradient-to-br from-purple-500 via-pink-500 to-orange-400 flex flex-col items-center justify-center gap-0.5"
          >
            <span className="text-[16px] leading-none">📸</span>
            <span>Story</span>
          </motion.button>
          <motion.button
            whileTap={{ scale: 0.94 }}
            onClick={() => {
              analytics.cta('whatsapp');
              const t = encodeURIComponent(shareText);
              window.open(`https://wa.me/?text=${t}`, '_blank');
            }}
            data-testid="share-whatsapp"
            className="h-12 rounded-xl text-white text-[11px] font-medium bg-green-600 flex flex-col items-center justify-center gap-0.5"
          >
            <span className="text-[16px] leading-none">💬</span>
            <span>WhatsApp</span>
          </motion.button>
          <motion.button
            whileTap={{ scale: 0.94 }}
            onClick={() => {
              const t = encodeURIComponent(shareText);
              window.open(`https://twitter.com/intent/tweet?text=${t}`, '_blank');
            }}
            data-testid="share-twitter"
            className="h-12 rounded-xl text-white text-[11px] font-medium bg-black border border-white/15 flex flex-col items-center justify-center gap-0.5"
          >
            <span className="text-[14px] leading-none">𝕏</span>
            <span>Post</span>
          </motion.button>
          <motion.button
            whileTap={{ scale: 0.94 }}
            onClick={handleSaveCard}
            disabled={cardSaving}
            data-testid="share-download"
            className="h-12 rounded-xl text-ivory text-[11px] font-medium bg-white/10 border border-white/20 flex flex-col items-center justify-center gap-0.5 disabled:opacity-50"
          >
            <span className="text-[14px] leading-none">{cardSaving ? '⏳' : '⬇'}</span>
            <span>{cardSaving ? 'Saving' : 'Save PNG'}</span>
          </motion.button>
        </div>
        {downloadError && <p className="text-xs text-rose-400/80 text-center mt-2">{downloadError}</p>}

        {/* Secondary: idea pack */}
        <button
          onClick={handleDownloadMd}
          data-testid="download-md"
          className="w-full mt-2 h-10 rounded-xl bg-white/5 border border-white/10 text-ivory/60 text-[12px] hover:bg-white/8 transition-all flex items-center justify-center gap-1.5"
        >
          📄 Download full idea pack (.md)
        </button>
      </div>

      {/* ── 3. Smart stats breakdown (explains the card) ── */}
      <div className="max-w-md mx-auto w-full px-4">
        <p className="text-[10px] text-ivory/40 uppercase tracking-widest mb-2">Stats on your card</p>
        <div className="space-y-1.5">
          <StatRow icon="🎖" label="Rarity" value={`${stats.rarity.tier} — ${stats.rarity.label}`} />
          <StatRow icon="⚡" label="Instinct speed" value={stats.responseSpeedRank.label} />
          <StatRow icon="💡" label="Idea novelty" value={stats.noveltyDecile.label} />
          <StatRow icon="🎯" label="Industry fit" value={stats.industryFitRank.label} />
          <StatRow icon="🧬" label="Trait signature" value={stats.traitSignature} mono />
        </div>
      </div>

      {/* ── 4. House identity ── */}
      <div className="max-w-md mx-auto w-full px-4 space-y-3">
        <h3 className="text-2xl font-serif font-bold" style={{ color: house.hex }}>{house.name}</h3>
        <p className="text-sm text-ivory/70 leading-relaxed">{house.description}</p>
        <div className="space-y-2">
          {house.lineage.map((fig) => (
            <div key={fig.name} className="bg-dark-surface border border-white/10 rounded-lg p-3">
              <p className="text-sm font-semibold text-ivory">{fig.name}</p>
              {fig.quantified_impact && (
                <p className="text-[11px]" style={{ color: `${house.hex}B0` }}>{fig.quantified_impact}</p>
              )}
              <p className="text-[10px] text-ivory/40 mt-0.5 uppercase tracking-wider">{fig.sharedTraitLine}</p>
            </div>
          ))}
        </div>
      </div>

      {/* ── 5. Top 3 ideas ── */}
      <div className="max-w-md mx-auto w-full px-4 space-y-2">
        <p className="text-xs font-mono text-ivory/30 uppercase tracking-widest">Your matched ideas</p>
        {allIdeas.map((si) => {
          const isCrowned = si.idea.idea_id === state.crownedIdeaId;
          return (
            <div key={si.idea.idea_id} className={`bg-dark-surface rounded-lg p-3 ${isCrowned ? 'border-2 border-gold/50' : 'border border-white/10'}`}>
              <div className="flex items-center justify-between">
                <p className={`text-sm font-semibold ${isCrowned ? 'text-gold' : 'text-ivory'}`}>{si.idea.idea_name}</p>
                <span className="text-[10px] font-mono text-ivory/30">{si.displayScore}%</span>
              </div>
              <p className="text-xs text-ivory/40 mt-1 line-clamp-1">{si.idea.one_liner}</p>
            </div>
          );
        })}
      </div>

      {/* ── 6. Mystic Vault at the bottom ── */}
      <div className="max-w-md mx-auto w-full px-4">
        <MysticVaultCard
          matchPercent={crowned?.displayScore}
          ideaName={crowned?.idea.idea_name}
          houseName={house.name}
          variant="full"
        />
      </div>

      <ScreenQuote screen="s11" />

      <p className="text-[10px] text-ivory/20 text-center font-mono px-4">
        {lines.s11.journeyComplete(house.name)}
      </p>
    </div>
  );
}

function StatRow({ icon, label, value, mono }: { icon: string; label: string; value: string; mono?: boolean }) {
  return (
    <div className="flex items-center justify-between gap-3 py-1.5 px-3 bg-dark-surface/40 border border-white/6 rounded-lg">
      <div className="flex items-center gap-2 shrink-0">
        <span className="text-[13px]">{icon}</span>
        <span className="text-[10px] uppercase tracking-wider text-ivory/45">{label}</span>
      </div>
      <span className={`text-[11px] text-ivory/80 text-right ${mono ? 'font-mono tracking-wider' : ''}`}>
        {value}
      </span>
    </div>
  );
}
