'use client';

import { useState, useEffect, useRef, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useJourneyStore } from '@/lib/store/journeyStore';
import { useUIStore } from '@/lib/store/uiStore';
import { lines } from '@/content/lines';
import { analytics } from '@/lib/analytics';
import housesRaw from '@/content/houses.json';
import type { ScoredIdea } from '@/lib/scoring/types';

interface LineageFigure { name: string; sharedTraitLine: string }
interface House {
  id: string; name: string; hex: string; tagline: string;
  description: string; strengths: string[]; lineage: LineageFigure[];
}
const HOUSES = housesRaw as unknown as House[];
const WHATSAPP_NUMBER = '919686917041';

// Crystal orb colors for the crystal display
const ORB_COLORS: Record<string, string> = {
  Grit: '#F59E0B', Vision: '#F0D060', Craft: '#CD7F32', Influence: '#9B59B6',
  Empathy: '#00D8B9', Analysis: '#5DADE2', Freedom: '#BDC3C7', Stability: '#27AE60',
};

/**
 * S11 — Founder Profile (enriched)
 *
 * Crystal display hero visual, two download buttons,
 * scarcity on consultation CTA.
 */
export function S11Profile() {
  const state = useJourneyStore();
  const enqueueMessage = useUIStore((s) => s.enqueueMessage);

  const [showConsultation, setShowConsultation] = useState(false);
  const [aboutExpanded, setAboutExpanded] = useState(false);
  const [downloadError, setDownloadError] = useState('');
  const [cardSaving, setCardSaving] = useState(false);
  const dialogueSent = useRef(false);
  const cardRef = useRef<HTMLDivElement>(null);

  const house = HOUSES.find((h) => h.id === state.houseId) || HOUSES[0];
  const crowned = state.matchedIdeas
    ? [state.matchedIdeas.nest, state.matchedIdeas.spark, state.matchedIdeas.wildvine]
        .find((s) => s.idea.idea_id === state.crownedIdeaId) || state.matchedIdeas.nest
    : null;
  const allIdeas = state.matchedIdeas
    ? [state.matchedIdeas.nest, state.matchedIdeas.spark, state.matchedIdeas.wildvine]
    : [];
  const displayName = state.displayName || 'Founder';
  const orbs = state.crystalOrbs.slice(0, 3);
  const orbColors = orbs.map((o) => ORB_COLORS[o] || '#D4A843');

  useEffect(() => {
    if (dialogueSent.current) return;
    dialogueSent.current = true;
    analytics.complete(state.houseId || 'unknown', crowned?.idea.idea_name || 'unknown');
    enqueueMessage({ speaker: 'cedric', text: lines.s11.cedric.intro, type: 'dialogue' });
    setTimeout(() => enqueueMessage({ speaker: 'cedric', text: lines.s11.cedric.final(displayName), type: 'dialogue' }), 3000);
    setTimeout(() => enqueueMessage({ speaker: 'pip', text: lines.s11.pip.final, type: 'dialogue' }), 5000);
  }, [enqueueMessage, displayName, state.houseId, crowned]);

  // Generate markdown idea pack
  const generateMarkdown = useCallback(() => {
    const whyYou = crowned ? (state.whyYouTexts[crowned.idea.idea_id] || 'Trust the match.') : '';
    const qs = crowned?.idea.quickStart;
    return `# ${crowned?.idea.idea_name || 'Your Idea'} — Your Catalst Founder Profile

**House:** ${house.name}
**Match:** ${crowned?.displayScore || 0}% in ${crowned?.idea.domain_primary.replace(/_/g, ' ') || 'unknown'}

## Your Top Idea
${crowned?.idea.idea_name || ''} — ${crowned?.idea.one_liner || ''}

${crowned?.idea.pain_to_promise || ''}

## Why This Fits You
${whyYou.replace('__loading__', 'Trust the match.')}

## First Steps
- Week 1: ${qs?.week1 || 'Validate the core assumption'}
- MVP: ${qs?.mvp || 'Build the simplest version'}
- First customers: ${qs?.firstCustomers || 'Talk to 10 people in the space'}

## Your Personality Profile
House: ${house.name} | Traits: ${orbs.join(', ')} | Strengths: ${house.strengths.join(', ')}

---
Generated by Catalst · catalst.app
`;
  }, [crowned, house, orbs, state.whyYouTexts]);

  function handleDownloadMd() {
    try {
      const md = generateMarkdown();
      const blob = new Blob([md], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `catalst-${house.id}-${displayName.toLowerCase().replace(/\s+/g, '-')}.md`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      analytics.cta('download');
    } catch { setDownloadError('Download failed, try again'); }
  }

  async function handleSaveCard() {
    if (!cardRef.current) return;
    setCardSaving(true);
    try {
      const { toPng } = await import('html-to-image');
      const dataUrl = await toPng(cardRef.current, { pixelRatio: 2 });
      const a = document.createElement('a');
      a.href = dataUrl;
      a.download = `catalst-${house.id}-${displayName.toLowerCase().replace(/\s+/g, '-')}.png`;
      a.click();
      analytics.cta('download');
    } catch { setDownloadError('Card save failed, try again'); }
    setCardSaving(false);
  }

  function getWhatsAppUrl() {
    return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(
      `Hi Anish! I just completed my Catalst journey.\nI'm a ${house.name} founder. My top idea is ${crowned?.idea.idea_name || 'my matched idea'} in ${crowned?.idea.domain_primary.replace(/_/g, ' ') || 'startups'}.\nI want to book a 30-min strategy call (₹500) to explore building it.`
    )}`;
  }

  return (
    <div className="flex flex-col gap-8 pb-8 overflow-y-auto">
      {/* ── Section 1: Founder Card ── */}
      <div className="mx-auto w-[300px] sm:w-[400px]">
        <div
          ref={cardRef}
          data-testid="founder-card"
          className="rounded-2xl p-6 flex flex-col items-center gap-3 text-center"
          style={{ border: `3px solid ${house.hex}`, background: '#14171E', aspectRatio: '9 / 16', boxShadow: `0 0 20px ${house.hex}30` }}
        >
          {/* House crest + name */}
          <p className="text-sm font-serif italic" style={{ color: house.hex }}>{house.name}</p>

          {/* Crystal display — hero visual: triangular arrangement of colored dots with lines */}
          <svg viewBox="0 0 100 80" className="w-28 h-20">
            {/* Connecting lines */}
            {orbs.length >= 2 && <line x1="50" y1="15" x2="25" y2="60" stroke={orbColors[0]} strokeWidth="1" opacity="0.4" />}
            {orbs.length >= 2 && <line x1="50" y1="15" x2="75" y2="60" stroke={orbColors[1]} strokeWidth="1" opacity="0.4" />}
            {orbs.length >= 3 && <line x1="25" y1="60" x2="75" y2="60" stroke={orbColors[2]} strokeWidth="1" opacity="0.4" />}
            {/* Orb dots */}
            {orbs.length >= 1 && <circle cx="50" cy="15" r="8" fill={orbColors[0]} opacity="0.7" />}
            {orbs.length >= 2 && <circle cx="25" cy="60" r="8" fill={orbColors[1]} opacity="0.7" />}
            {orbs.length >= 3 && <circle cx="75" cy="60" r="8" fill={orbColors[2]} opacity="0.7" />}
            {/* Glow center */}
            <circle cx="50" cy="45" r="4" fill={house.hex} opacity="0.5" />
          </svg>

          {/* User name */}
          <h2 className="text-xl font-bold tracking-wider uppercase text-ivory">{displayName}</h2>

          {/* Trait badges */}
          <div className="flex gap-2 flex-wrap justify-center">
            {orbs.map((orb) => (
              <span key={orb} className="text-[10px] px-2 py-0.5 rounded-full font-medium"
                style={{ backgroundColor: `${house.hex}30`, color: house.hex, border: `1px solid ${house.hex}40` }}>
                {orb}
              </span>
            ))}
          </div>

          {/* Radar silhouette */}
          <svg viewBox="0 0 100 100" className="w-20 h-20 opacity-40">
            <polygon points="50,15 85,40 75,80 25,80 15,40" fill={`${house.hex}15`} stroke={house.hex} strokeWidth="1" />
          </svg>

          {/* Match info */}
          {crowned && (
            <p className="text-xs font-mono uppercase tracking-wider" style={{ color: '#D4A843' }}>
              {crowned.displayScore}% match · {crowned.idea.domain_primary.replace(/_/g, ' ')}
            </p>
          )}

          <p className="text-xs text-ivory/40 italic">{house.tagline}</p>
          <p className="text-[10px] text-ivory/30">{house.lineage.map((f) => f.name).join(' · ')}</p>
          <p className="text-[9px] text-ivory/20 mt-auto">catalst.app</p>
        </div>
      </div>

      {/* ── Section 2: House identity ── */}
      <div className="space-y-3">
        <h3 className="text-2xl font-serif font-bold" style={{ color: house.hex }}>{house.name}</h3>
        <p className="text-sm text-ivory-muted leading-relaxed">{house.description}</p>
        <div className="space-y-2">
          {house.lineage.map((fig) => (
            <div key={fig.name} className="bg-dark-surface border border-white/10 rounded-lg p-3">
              <p className="text-sm font-semibold text-ivory">{fig.name}</p>
              <p className="text-[10px] text-ivory/40">{fig.sharedTraitLine}</p>
            </div>
          ))}
        </div>
      </div>

      {/* ── Section 3: Top 3 Ideas ── */}
      <div className="space-y-2">
        <p className="text-xs font-mono text-ivory/30 uppercase tracking-widest">Your matched ideas</p>
        {allIdeas.map((si: ScoredIdea) => {
          const isCrowned = si.idea.idea_id === state.crownedIdeaId;
          return (
            <div key={si.idea.idea_id} className={`bg-dark-surface rounded-lg p-3 ${isCrowned ? 'border-2 border-gold/50' : 'border border-white/10'}`}>
              <div className="flex items-center justify-between">
                <p className={`text-sm font-semibold ${isCrowned ? 'text-gold' : 'text-ivory'}`}>{si.idea.idea_name}</p>
                <span className="text-[10px] font-mono text-ivory/30">{si.displayScore}%</span>
              </div>
              <p className="text-xs text-ivory/40 mt-1 line-clamp-1">{si.idea.one_liner}</p>
            </div>
          );
        })}
      </div>

      {/* ── Section 4: Consultation (hidden until triggered) ── */}
      <AnimatePresence>
        {showConsultation && (
          <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }} exit={{ opacity: 0, height: 0 }} className="overflow-hidden">
            <div className="bg-dark-surface border border-gold/20 rounded-2xl p-6 space-y-4">
              <p className="text-xs text-ivory/40 italic">The seed is ready. Now someone has to plant it.</p>
              <p className="text-[11px] font-mono text-ivory-muted uppercase tracking-widest">YOUR IDEA. 1 WEEK. CLAUDE CODE.</p>
              <h4 className="text-[22px] font-serif text-ivory leading-snug">Stop planning. Start shipping.</h4>
              <p className="text-sm text-ivory-muted leading-relaxed">I build founder MVPs with Claude Code and a team of AI specialists. One call to see if we're the right fit.</p>
              <span className="inline-block text-xs px-3 py-1 rounded-full border border-gold/40 text-ivory">₹500 · 30 min · No fluff</span>
              <p className="text-xs text-gold/80 font-semibold">⚡ Limited slots — 3 founders this month</p>
              <a href={getWhatsAppUrl()} target="_blank" rel="noopener noreferrer" data-testid="consultation-whatsapp"
                onClick={() => analytics.cta('whatsapp')}
                className="flex items-center justify-center gap-2 w-full py-3.5 rounded-full bg-gold text-dark font-semibold text-sm hover:bg-gold/90 transition-all" style={{ height: 56 }}>
                💬 Book Your Strategy Call →
              </a>

              {/* About the builder */}
              <div className="border-t border-white/10 pt-3">
                <button onClick={() => setAboutExpanded(!aboutExpanded)} data-testid="about-toggle"
                  className="flex items-center gap-2 text-xs text-ivory/40 hover:text-ivory/60 cursor-pointer w-full">
                  <span style={{ transform: aboutExpanded ? 'rotate(90deg)' : 'rotate(0)', transition: 'transform 0.2s' }}>›</span>
                  About the builder
                </button>
                <AnimatePresence>
                  {aboutExpanded && (
                    <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} transition={{ duration: 0.3 }} className="overflow-hidden">
                      <div className="pt-3 space-y-2">
                        <p className="text-base font-semibold text-ivory">Anish Dutta</p>
                        <p className="text-[13px] text-ivory-muted">Product Manager · AI Builder · Mumbai</p>
                        <div className="flex flex-wrap gap-1.5">
                          {['Get Set Learn · EdTech PM', "Masters' Union · Merit Scholar", 'IIT Bombay · Agentic AI', 'Catalst · 7 iterations · 2 years'].map((c) => (
                            <span key={c} className="text-[10px] px-2 py-0.5 rounded-full bg-white/5 text-ivory/50 border border-white/10">{c}</span>
                          ))}
                        </div>
                        <a href="https://in.linkedin.com/in/anish-dutta-4ba701282" target="_blank" rel="noopener noreferrer" data-testid="linkedin-link"
                          className="inline-block text-[11px] text-gold/60 hover:text-gold underline underline-offset-2">linkedin.com/in/anish-dutta-4ba701282</a>
                        <p className="text-[13px] text-ivory-muted italic">I've built this thing 7 times. I know what it takes to ship.</p>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* ── Section 5: Downloads + consultation trigger ── */}
      <div className="space-y-3">
        <div className="flex gap-2">
          <button onClick={handleSaveCard} disabled={cardSaving}
            className="flex-1 py-3 rounded-full border border-ivory/20 text-ivory font-semibold text-sm hover:border-ivory/40 hover:bg-white/5 transition-all">
            {cardSaving ? 'Saving...' : '🖼 Save Card Image'}
          </button>
          <button onClick={handleDownloadMd} data-testid="download-btn"
            className="flex-1 py-3 rounded-full border border-ivory/20 text-ivory font-semibold text-sm hover:border-ivory/40 hover:bg-white/5 transition-all">
            📄 Download Idea Pack
          </button>
        </div>
        {downloadError && <p className="text-xs text-error text-center">{downloadError}</p>}

        {!showConsultation && (
          <button onClick={() => { setShowConsultation(true); analytics.cta('consultation'); }} data-testid="consultation-trigger"
            className="w-full text-center text-xs text-ivory/30 hover:text-gold/60 transition-colors underline underline-offset-2 cursor-pointer">
            Want expert help building this?
          </button>
        )}
      </div>

      <p className="text-[10px] text-ivory/20 text-center font-mono">{lines.s11.journeyComplete(house.name)}</p>
    </div>
  );
}
